#à configurer

#version: 3
#
#db:
#  location: database name
#  login: database login
#  mdp: databse mdp
#  host:
#  port:
#  pathsh:
#  pathsql:

bash:
  alias: "/var/www/html/hospiway/vendor/bin/drush"
